name: Move (Aptos) Tree Sitter Parser Test

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      search-path-in-repo:
        required: false
        type: string

jobs:
  test-on-aptos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout itself
        uses: actions/checkout@v4
      - name: Checkout `${{ inputs.repo }}`
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          path: test/repos/${{ inputs.repo }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: sudo apt update && sudo apt install -y gcc
      - run: npm install -g tree-sitter-cli
      - run: tree-sitter init-config
      - run: tree-sitter generate
      - run: python batch-test.py test/repos/${{ inputs.repo }}/${{ inputs.search-path-in-repo }}
  test-on-chain:
    runs-on: ubuntu-latest
